name: Learning GitHub Action
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: Learning GitHub Actions
    runs-on: ubuntu-latest # validate version
    steps:
      - uses: actions/checkout@v2 
      - name: Install GitHub CLI
        run: sudo apt-get install gh
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - name: Install GitHub CLI
        run: sudo apt-get install gh 
      - name: Comment on PR
        run: gh pr comment $PR_URL --body "WELCOME TO THE REPOSITORY!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

